runtime: nodejs14

handlers:
- url: /(.*\.(appcache|manifest))
  mime_type: text/cache-manifest
  static_files: build/\1
  upload: build/(.*\.(appcache|manifest))
  expiration: "0m"

- url: /(.*\.atom)
  mime_type: application/atom+xml
  static_files: build/\1
  upload: build/(.*\.atom)
  expiration: "1h"

- url: /(.*\.crx)
  mime_type: application/x-chrome-extension
  static_files: build/\1
  upload: build/(.*\.crx)

- url: /(.*\.css)
  mime_type: text/css
  static_files: build/\1
  upload: build/(.*\.css)

- url: /(.*\.eot)
  mime_type: application/vnd.ms-fontobject
  static_files: build/\1
  upload: build/(.*\.eot)

- url: /(.*\.htc)
  mime_type: text/x-component
  static_files: build/\1
  upload: build/(.*\.htc)

- url: /(.*\.html)
  mime_type: text/html
  static_files: build/\1
  upload: build/(.*\.html)
  expiration: "1h"

- url: /(.*\.ico)
  mime_type: image/x-icon
  static_files: build/\1
  upload: build/(.*\.ico)
  expiration: "7d"

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: build/\1
  upload: build/(.*\.js)

- url: /(.*\.json)
  mime_type: application/json
  static_files: build/\1
  upload: build/(.*\.json)
  expiration: "1h"

- url: /(.*\.m4v)
  mime_type: video/m4v
  static_files: build/\1
  upload: build/(.*\.m4v)

- url: /(.*\.mp4)
  mime_type: video/mp4
  static_files: build/\1
  upload: build/(.*\.mp4)

- url: /(.*\.(ogg|oga))
  mime_type: audio/ogg
  static_files: build/\1
  upload: build/(.*\.(ogg|oga))

- url: /(.*\.ogv)
  mime_type: video/ogg
  static_files: build/\1
  upload: build/(.*\.ogv)

- url: /(.*\.otf)
  mime_type: font/opentype
  static_files: build/\1
  upload: build/(.*\.otf)

- url: /(.*\.rss)
  mime_type: application/rss+xml
  static_files: build/\1
  upload: build/(.*\.rss)
  expiration: "1h"

- url: /(.*\.safariextz)
  mime_type: application/octet-stream
  static_files: build/\1
  upload: build/(.*\.safariextz)

- url: /(.*\.(svg|svgz))
  mime_type: images/svg+xml
  static_files: build/\1
  upload: build/(.*\.(svg|svgz))

- url: /(.*\.swf)
  mime_type: application/x-shockwave-flash
  static_files: build/\1
  upload: build/(.*\.swf)

- url: /(.*\.ttf)
  mime_type: font/truetype
  static_files: build/\1
  upload: build/(.*\.ttf)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: build/\1
  upload: build/(.*\.txt)

- url: /(.*\.unity3d)
  mime_type: application/vnd.unity
  static_files: build/\1
  upload: build/(.*\.unity3d)

- url: /(.*\.webm)
  mime_type: video/webm
  static_files: build/\1
  upload: build/(.*\.webm)

- url: /(.*\.webp)
  mime_type: image/webp
  static_files: build/\1
  upload: build/(.*\.webp)

- url: /(.*\.woff)
  mime_type: application/x-font-woff
  static_files: build/\1
  upload: build/(.*\.woff)

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: build/\1
  upload: build/(.*\.xml)
  expiration: "1h"

- url: /(.*\.xpi)
  mime_type: application/x-xpinstall
  static_files: build/\1
  upload: build/(.*\.xpi)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: build/\1
  upload: build/(.*\.(bmp|gif|ico|jpeg|jpg|png))

# audio files
- url: /(.*\.(mid|midi|mp3|wav))
  static_files: build/\1
  upload: build/(.*\.(mid|midi|mp3|wav))  

# windows files
- url: /(.*\.(doc|exe|ppt|rtf|xls))
  static_files: build/\1
  upload: build/(.*\.(doc|exe|ppt|rtf|xls))

# compressed files
- url: /(.*\.(bz2|gz|rar|tar|tgz|zip))
  static_files: build/\1
  upload: build/(.*\.(bz2|gz|rar|tar|tgz|zip))

# index files
- url: /(.+)/
  static_files: build/\1/index.html
  upload: build/(.+)/index.html
  expiration: "15m"

- url: /(.+)
  static_files: build/\1/index.html
  upload: build/(.+)/index.html
  expiration: "15m"

# site root
- url: /
  static_files: build/index.html
  upload: build/index.html
  expiration: "15m"