env: standard
runtime: nodejs14
service: default

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.ico)
    mime_type: image/x-icon
    static_files: build/\1
    upload: build/(.*\.ico)

  - url: /(.*\.(json|ico|js))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js)$
  
  # image files
  - url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
    static_files: build/\1
    upload: build/(.*\.(bmp|gif|ico|jpeg|jpg|png))

  - url: .*
    static_files: build/index.html
    upload: build/index.html